version: '3.5'
services: 
  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: cruddb
      MYSQL_USER: root
      MYSQL_PASSWORD: cruddb
    ports:
      - 3306:3306
  crudapp:
    image: malejandro13/nginx-php73-dev:latest
    container_name: crudapp
    volumes:
      - .:/var/www/html
    ports:
      - 8000:80
    depends_on:
      - mysql
      - redis
  redis:
    image: redis:5-alpine
    container_name: redis
    ports: 
      - 6379:6379